#!/bin/bash
#BSUB -q <queue>
#BSUB -J JobName[<start>-<stop>]%<slot limit>
#BSUB -oo ./JobName.%I.oe

# Notes:
# 1) start to stop is inclusive
# 2) the slot limit is optional, but makes
#    sure the job uses no more than <slot limit> cores
# 3) the %I is the job index
# 4) the same index is given as the environment
#    variable $LSB_JOBINDEX
# see this guide http://www.ccs.miami.edu/hpc/lsf/7.0.6/admin/jobarrays.html

<exec1> <args1> $LSB_JOBINDEX

